### PR TITLE
fix mapper process twin delta

### PR DESCRIPTION
**Pull request by gy95**
when mapper unmarshal visitor config failed, cannot continue to set visitor, it should continue next loop

Signed-off-by: gy95 <guoyao17@huawei.com>

### CODE REVIEW

**Review by sailorvii — APPROVED** [review]
/approved

**Review by sailorvii — APPROVED** [review]
/approved

**Comment by gy95** [comment]
> New changes are detected. LGTM label has been removed.

rebase succeed, cc @sailorvii

**Pull request merged**
