### PR TITLE
Move Kubeedge Mappers-go

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

### CODE REVIEW

**Comment by luogangyi** [comment]
I am trying to move all mappers and corresponding tests here, but not find a way to reserve commit id,

I see you did reserve commit id, would you explain how to do that? so I can help move other mappers.

**Comment by daixiang0** [comment]
You can add a remote with kubeedge main repo, then use `git cherry-pick` or `git filter-branch` to get related changes.

**Comment by sailorvii** [comment]
Hi,

Could you also help to merge the bluetooth folder in mapper?

Thanks

**Comment by daixiang0** [comment]
I will do it after this merged.

**Comment by kevin-wangzefeng** [comment]
manually merging as prow bot not yet enabled for this repo.

**Pull request merged**
