### PR TITLE
add usbcamera-dmi

### PR DESCRIPTION
**Pull request by luomengY**
A USB protocol camera mapper developed based on the dmi and mapper framework.
@cl2017  @wbc6080

### CODE REVIEW

**Comment by wbc6080** [comment]
Is the vendor folder necessary? Can we use go.mod directly? Otherwise, there will be too many files and review will be difficult

**Comment by luomengY** [comment]
> Is the vendor folder necessary? Can we use go.mod directly? Otherwise, there will be too many files and review will be difficult

ok, I have deleted the vendor.

**Comment by wbc6080** [comment]
Would it be better to change the directory name to  `mappers/kubeedge-v1.15.0/usbcamera-dmi/...` ?

**Comment by luomengY** [comment]
> kubeedge-v1.15.0

ok

**Review by fisherxu — COMMENTED** [review]
/approve
thanks for the mapper.

**Pull request merged**
